/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primitiva;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author raguiarperez
 */
public class Primitiv extends javax.swing.JFrame {

    /**
     * Creates new form Primitiv
     */
    public Primitiv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_numeros = new javax.swing.JList<>();
        Btn_Participar = new javax.swing.JButton();
        Lab_Cantidad_aciertos = new javax.swing.JLabel();
        Lab_cantidad_ganada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numeros Ganadores:");

        jScrollPane1.setViewportView(Lista_numeros);

        Btn_Participar.setText("Participar");
        Btn_Participar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ParticiparActionPerformed(evt);
            }
        });

        Lab_Cantidad_aciertos.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de Aciertos"));

        Lab_cantidad_ganada.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad Ganada"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Lab_Cantidad_aciertos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lab_cantidad_ganada, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(Btn_Participar)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Btn_Participar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Lab_Cantidad_aciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lab_cantidad_ganada, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ParticiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ParticiparActionPerformed
        
        int num1, num2, num3, num4, num5, num6;
        int cantidadAciertos=0;
        double cantidadGanada=0;
        
        
        
        
        num1=Integer.parseInt(JOptionPane.showInputDialog("Introduce el primer numero"));
        num2=Integer.parseInt(JOptionPane.showInputDialog("Introduce el segundo numero"));
        num3=Integer.parseInt(JOptionPane.showInputDialog("Introduce el tercero numero"));
        num4=Integer.parseInt(JOptionPane.showInputDialog("Introduce el cuarto numero"));
        num5=Integer.parseInt(JOptionPane.showInputDialog("Introduce el quinto numero"));
        num6=Integer.parseInt(JOptionPane.showInputDialog("Introduce el sexto numero"));
        
        DefaultListModel numeros= new DefaultListModel();
        
        for (int j = 0; j < 6; j++) {
            numeros.addElement((int)(Math.random()*49+1));
            Lista_numeros.setModel(numeros);
                        
        }
        
        
        
        for (int g = 0; g < 6; g++) {
            if (numeros.getElementAt(g).equals(num1)) {
                cantidadAciertos++;
            }
            if (numeros.getElementAt(g).equals(num2)) {
                cantidadAciertos++;
            }
            if (numeros.getElementAt(g).equals(num3)) {
                cantidadAciertos++;
            }
            if (numeros.getElementAt(g).equals(num4)) {
                cantidadAciertos++;
            }
            if (numeros.getElementAt(g).equals(num5)) {
                cantidadAciertos++;
            }
            if (numeros.getElementAt(g).equals(num6)) {
                cantidadAciertos++;
            }
            Lab_Cantidad_aciertos.setText(""+cantidadAciertos);
            
            if (cantidadAciertos==6) {
                cantidadGanada=1000;
            }else{
                if(cantidadAciertos==5){
                cantidadGanada=750;
                                        
            }else{
                  if (cantidadAciertos==4) {
                    cantidadGanada=500;  
                          
                      }else{
                      cantidadGanada=0;
                      }
                  }
  
                
                  }
            Lab_cantidad_ganada.setText(""+cantidadGanada);
        }
        
    }//GEN-LAST:event_Btn_ParticiparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Primitiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Primitiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Primitiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Primitiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Primitiv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Participar;
    private javax.swing.JLabel Lab_Cantidad_aciertos;
    private javax.swing.JLabel Lab_cantidad_ganada;
    private javax.swing.JList<String> Lista_numeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
